[manager]
show_hidden = true
linemode = "size"

[opener]
edit = [{ run = 'nvim "$@"', block = true, for = "unix" }]
play = [{ run = 'vlc "$@"', orphan = true, for = "unix" }]
open = [{ run = 'xdg-open "$@"', desc = "Open" }]
